services:
  - type: web
    name: v-pulse-api
    runtime: docker
    repo: https://github.com/vietdungnguyen2005/Project3
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    healthCheckPath: /actuator/health/readiness
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_DATA_REDIS_URL
        sync: false
      - key: BFF_SHARED_SECRET
        sync: false
      - key: VPULSE_OPS_SECRET
        sync: false
      - key: VPULSE_DEMO_DATA_ENABLED
        value: "true"
      - key: DEPLOYMENT_ENVIRONMENT
        value: production

