apiVersion: v1
kind: Service
metadata:
  name: {{ include "vpulse.name" . }}
  labels: {{- include "vpulse.labels" . | nindent 4 }}
spec:
  selector: { app.kubernetes.io/name: vpulse }
  ports: [{ name: http, port: {{ .Values.service.port }}, targetPort: http }]
